### ISSUE TITLE
Finally

### ISSUE THREAD

**Issue by vic3lord** [cudacoder/governor#1]
התחלת לכתוב בשפה נורמלית

**Comment by cudacoder** [comment]
חחחחחחחח תשמעעע אחי 
it's been a long time coming,
ולמי יש יד בזה אם לא לך תגיד ליייי
תבדוק את הקוד הוא זוועה אשמח לביקורת 🙏🏼

**Comment by cudacoder** [comment]
@vic3lord 
חחחחחחחח תשמעעע 
it's been a long time coming,
ולמי יש יד בזה אם לא לך תגיד ליייי
תבדוק את הקוד הוא זוועה אשמח לביקורת 🙏🏼

**Comment by vic3lord** [comment]
תענוג, אני אשמח לעזור ולהסתכל
